"""autogenerated by genpy from arbiter/frame.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class frame(genpy.Message):
  _md5sum = "d76cf64e7d0d3743e5324ff510752d0f"
  _type = "arbiter/frame"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 msg_id
bool remote_request
int8 DLC
uint8[] data
int32 CRC_seq
bool ACK

"""
  __slots__ = ['msg_id','remote_request','DLC','data','CRC_seq','ACK']
  _slot_types = ['int32','bool','int8','uint8[]','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msg_id,remote_request,DLC,data,CRC_seq,ACK

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(frame, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.msg_id is None:
        self.msg_id = 0
      if self.remote_request is None:
        self.remote_request = False
      if self.DLC is None:
        self.DLC = 0
      if self.data is None:
        self.data = ''
      if self.CRC_seq is None:
        self.CRC_seq = 0
      if self.ACK is None:
        self.ACK = False
    else:
      self.msg_id = 0
      self.remote_request = False
      self.DLC = 0
      self.data = ''
      self.CRC_seq = 0
      self.ACK = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_iBb.pack(_x.msg_id, _x.remote_request, _x.DLC))
      _x = self.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_iB.pack(_x.CRC_seq, _x.ACK))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.msg_id, _x.remote_request, _x.DLC,) = _struct_iBb.unpack(str[start:end])
      self.remote_request = bool(self.remote_request)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.CRC_seq, _x.ACK,) = _struct_iB.unpack(str[start:end])
      self.ACK = bool(self.ACK)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_iBb.pack(_x.msg_id, _x.remote_request, _x.DLC))
      _x = self.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_iB.pack(_x.CRC_seq, _x.ACK))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.msg_id, _x.remote_request, _x.DLC,) = _struct_iBb.unpack(str[start:end])
      self.remote_request = bool(self.remote_request)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.data = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.CRC_seq, _x.ACK,) = _struct_iB.unpack(str[start:end])
      self.ACK = bool(self.ACK)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_iBb = struct.Struct("<iBb")
_struct_iB = struct.Struct("<iB")
